### ISSUE TITLE
Apply spatial constraints up front in stand boundaries step [2 weeks]

### ISSUE THREAD

**Issue by perrygeo** [Ecotrust/forestplanner#114]
Starting digitizing from scratch: get a dialog that says "Start with Stream Buffers and steep slopes already delineated?". Those layers are clipped/intersected and added as you initial stands.

Bigger questions around what to do for people with pre-created GIS stand data or people who want to apply these buffers _after_ they've started digitizing.

**Comment by d-diaz** [comment]
dup of #110
