### ISSUE TITLE
Incorrect stand list makes it past validation

### ISSUE THREAD

**Issue by perrygeo** [Ecotrust/forestplanner#278]
Based on Sam's comments around loosing stands/forest types. Not sure at all why they would disappear from the interface and I can't reproduce that (it might have been during a period of system maintenance?) but...

He had 22 stands, 3 of which couldn't be assigned a cond_id because the stand list was screwy:

```
{u'classes': [[u'Western hemlock', 12, 24, 58],
  [u'Sitka spruce', 12, 24, 11],
  [u'Red alder', 12, 24, 34],
  [u'Douglas-fir', 12, 24, None]],
 u'property': u'trees_forestproperty_270'}
```

Note the `None` TPA for DF 12-24". 

Not sure how this made it past both the client and server side validation but it's right there in the database and basically renders this property unusable until Sam edits and reapplys that veg type.

**Comment by d-diaz** [comment]
Can't reproduce. Can't save row in stand table without having TPA entered.
