### ISSUE TITLE
Drive space for production database

### ISSUE THREAD

**Issue by perrygeo** [Ecotrust/forestplanner#289]
The full idb batch (see #281 ) will create a table with an estimated ~900 million rows and ~ 291 GB of disk space including indicies.  This exceeds the size of the current database partition. We need to expand to at least 500 GB - what are our options?

**Comment by d-diaz** [comment]
Related to #358. To improve matching options for nearest neighbor, do we need to sample from the IDB database, or can we just push a batch with the whole thing?
