### ISSUE TITLE
Identify which plots are currently used in nearest neighbor matches

### ISSUE THREAD

**Issue by d-diaz** [Ecotrust/forestplanner#359]
Related to #358. Develop a database query to identify which plots (condition IDs) are in use by nearest neighbor matches for existing users and which are not.

**Comment by rhodges** [comment]
Files sent by email August 17th, 2015.
Copied over to:
//neoterra/gis/projects/ForestPlanner_2015/Data/
cond_id_use.csv
all_cond_ids.csv
