### ISSUE TITLE
Reformat PLSS (Township & Range) labels

### ISSUE THREAD

**Issue by d-diaz** [Ecotrust/forestplanner#381]
Would like to add some spacing and drop leading zeroes from PLSS grid and section labels to a bit more legible and user-friendly. Would like to re-parse the labels to be 

Something like:

```
120 N, 70 W
Section 2    
# second line only included when at zoom level where sections are displayed in map
```

Instead of the current:

```
120N070W.S2
```

**Comment by jtutak** [comment]
I think that's doable. I'll need @dnseminara's input on the best way to serve him these attributes for the multi-zoom level options. 

Do you have a timeline?

**Comment by dnseminara** [comment]
happy to meet whenever about the best way to show this...
