### ISSUE TITLE
mapquest tiles no longer active

### ISSUE THREAD

**Issue by d-diaz** [Ecotrust/forestplanner#384]
In time-series maps (under step 4, Evaluate Future Scenarios), mapquest is being used as the basemap and is no longer displaying images, and a message is showing up in the tiles saying 
```
Mapquest + Developer
As of July 11, 2016, direct tile access has been discontinued
...
```
Update this to point to the same Google Hybrid baselayer used on all other maps in the tool.

**Comment by rhodges** [comment]
Fixed: 93f45470842e0fafa2979da3c019fb0249edc021
