### ISSUE TITLE
Cost chart not loading

### ISSUE THREAD

**Issue by d-diaz** [Ecotrust/forestplanner#386]
![image](https://cloud.githubusercontent.com/assets/4120452/24778032/42df98f0-1add-11e7-8514-e08eafcaf3ad.png)

**Comment by pollardld** [comment]
looking into this

**Comment by pollardld** [comment]
@rhodges could you help me locate the log for cost errors? There is a [directory to capture logs](https://github.com/Ecotrust/forestplanner/tree/master/logs/cost_errors), but I'm not sure where the production log lives.

**Comment by rhodges** [comment]
according to nginx configurations:
 * access_log /var/log/nginx/forestplanner.access.log;
 * error_log /var/log/nginx/forestplanner.error.log;

Logs from the 6th will need to be unzipped.

**Comment by rhodges** [comment]
I'm not seeing anything telling in the logs from @d-diaz 's error, but it looks like we are able to replicate the issue.

What I'm seeing is that REST requests like this:
http://forestplanner.ecotrust.org/features/scenario/links/scenario-cash-flow/trees_scenario_207/ 
return 'null'

To test for yourself you'll have to replace '.../trees_scenario_207/' with your own scenario ID number.

**Comment by pollardld** [comment]
I see 'null' as well

**Comment by pollardld** [comment]
The service Uli had relied on to find the nearest known road to calculate costs years ago updated its API, thereby breaking the cost modeling function.

There were two instances of calling this api - one to calculate distance from nearest road, one to find the shortest route from the landing to the mill.
